###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/channel_mapper/impl/gem5_port_interleave.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class Gem5PortInterleave(Component):
    impl = "Gem5PortInterleave"
    interleave_size = Param(int, required=True)
